### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by anik786** [plivo/voicechat#10]
The demo at http://voicechatapi.com/ dosen't work.

When you go to the site and click "create your private conference room" it sends you to a page with a link and a button to "join your conference".

Neither does using the link nor the the button work. It simply displays a panel mentioning to click arrow when you see the permission on the browser, but the permission doesn't actually show up. 

When looking at the console the following errors are shown:

![error](https://cloud.githubusercontent.com/assets/5897460/11719359/4d591160-9f52-11e5-8f0c-6f825ba09f9a.png)

**Comment by cachrisman** [comment]
Thanks for the notice! It should be working now. Let me know if you're having any more problems!
