### ISSUE TITLE
issue on addons

### ISSUE THREAD

**Issue by nikhil009** [plivo/voicechat#11]
Hi,
It seems that for heroku the app requires a credit card, when you deploy this app (addons). Anyone experienced this? how to overcome on this issue.

$ heroku addons:add redistogo:nano --app voicecchat

This error was occur 

heroku-cli: Installing core plugins... done
WARNING: `heroku addons:add` has been deprecated. Please use `heroku addons:create` instead.
 !    Please verify your account to install this add-on plan (please enter a credit card) For more information, see https://devcenter.heroku.com/categories/billing Verify now at https://heroku.com/verify

**Comment by cachrisman** [comment]
Heroku requires a credit card to verify your account but the redistogo:nano addon doesn't cost anything. Once you have verified your heroku account simply use `heroku addons:create redistogo:nano` to add the free redistogo:nano addon.

**Comment by nikhil009** [comment]
Ok thanks.
